# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5786f198a9798c18a0077bce9a05933874e3e9c458b56cb2cd6fa7a2559248fccc835f7c6c3ce0459f42d4ea3afae3841ba0ebcd3eeee68e92567ec47a07e7f

test:
  secret_key_base: cf6e2b3411472dfef43a4d8d713d6b5c0398b3705d415f65f781859315d0467360d4a021b292c9a0e3d5208b23e0b21954d7b12bb3e6ca390c855ef1f3118f9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
